services:
  shiny-app:
    build: .
    image: shiny-app
    command: Rscript --verbose /home/shiny-app/app.R
    volumes:
      - ./app.R:/home/shiny-app/app.R
      - ./files/css/style.css:/srv/shiny-server/www/css/style.css
    ports:
      - 8180:8180